name: "publish"
on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: check current folder
        run: ls
      - name: checkout other repo
        uses: actions/checkout@v2
        with:
          repository: genshinsim/gcsim
          path: gcsim
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17.2"
      - name: build cmd line tool
        run: go build
        working-directory: ./gcsim/cmd/gcsim
      - name: check files
        run: ls ./gcsim/cmd/gcsim
      - name: move to binaries folder (not windows)
        if: matrix.platform != 'windows-latest'
        run: cp ./gcsim/cmd/gcsim/gcsim ./src-tauri/binaries/gcsim
      - name: move to binaries folder (windows)
        if: matrix.platform == 'windows-latest'
        run: cp ./gcsim/cmd/gcsim/gcsim.exe ./src-tauri/binaries/gcsim.exe
      - name: check binaries folder
        run: ls ./src-tauri/binaries
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 17
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ secrets.CLEAR_CACHE }}
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: install app dependencies
        run: yarn
      - name: run move binaries
        run: node scripts/move-binary.js
      # - name: build tauri app
      #   run: yarn tauri build
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: gcsim-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "gcsim v__VERSION__"
          releaseBody: "For Windows users, download the .msi file. For Mac users download the .dmg file. Linux users can figure it out. See https://github.com/genshinsim/gcsimui/blob/main/release-notes.txt for release notes."
          releaseDraft: false
          prerelease: false
  update-latest:
    needs: publish-tauri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install jq
        run: sudo apt-get install jq -y
      - name: run shell script
        run: chmod u+x ./scripts/latest.sh && ./scripts/latest.sh
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/srliao/92d3d16d4f2921746b5791ffa23eded0
          gist_title: gcsim
          gist_description: gcsim latest release
          github_file: ./latest.json
